name: CI/CD Build & Update Manifests

on:
  push:
    branches: [ main ]

env:
  MANIFESTS_REPO: git@github.com:felipemgilioli/hello-manifests.git
  MANIFESTS_DIR: manifests

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/hello-app:${{ github.sha }}

      - name: Prepare SSH to push to manifests repo
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H github.com >> ~/.ssh/known_hosts

      - name: Clone manifests repo
        run: |
          git clone $MANIFESTS_REPO $MANIFESTS_DIR

      - name: Update image tag in manifests and push
        run: |
          IMAGE=${{ secrets.DOCKER_USERNAME }}/hello-app:${{ github.sha }}
          sed -i "s|IMAGE_PLACEHOLDER|$IMAGE|g" $MANIFESTS_DIR/deployment.yaml
          cd $MANIFESTS_DIR
          git config user.email "actions@github.com"
          git config user.name "github-actions"
          git add deployment.yaml
          git commit -m "ci: update image to $IMAGE" || echo "no changes to commit"
          git push origin main
